name: SduElectricityReminder

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'  # UTC 0:00，对应北京时间 8:00
  workflow_dispatch:  # 允许手动触发

jobs:
  sdu-electricity-spider:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.7]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Spider in VPN
        run: |
            curl -m 3 --retry 3 -s -o /dev/null https://mcard.sdu.edu.cn/charge/feeitem/getThirdData
            python auto-script.py --sendkey ${{ secrets.SENDKEY }} --Synjones_Auth "${{ secrets.SYNJONES_AUTH }}"